//DepositProcess
export const shukinOptions = [
  { value: "集金", code: "0" },
  { value: "クレジット", code: "13" },
];
export const nyukinOptions = [
  { value: "現金", code: "1" },
  { value: "小切手", code: "2" },
  { value: "振込", code: "3" },
  { value: "手形", code: "4" },
  { value: "相殺", code: "5" },
  { value: "自振", code: "7" },
  { value: "コンビニ", code: "8" },
  { value: "その他", code: "9" },
];

//ProductSearchModal
export const mockData = [
  {
    id: 1,
    productCode: "1900004",
    makerCode: "メーカ084",
    no: "KP-20",
    name: "二連二重コンローバー",
    warehouse: "0001-001",
    price: "12,000.00",
    stock: "10.00",
    allocated: "2.00",
    available: "8.00",
  },
  {
    id: 2,
    productCode: "1900004",
    makerCode: "メーカ084",
    no: "KP-20",
    name: "二連二重コンローバー",
    warehouse: "事務所0001-001",
    price: "12,000.00",
    stock: "10.00",
    allocated: "2.00",
    available: "8.00",
  },
  {
    id: 3,
    productCode: "1900004",
    makerCode: "メーカ084",
    no: "KP-20",
    name: "二連二重コンローバー",
    warehouse: "0001-001",
    price: "12,000.00",
    stock: "10.00",
    allocated: "2.00",
    available: "8.00",
  },
  {
    id: 4,
    productCode: "1900004",
    makerCode: "メーカ084",
    no: "KP-20",
    name: "二連二重コンローバー",
    warehouse: "事務所0001-001",
    price: "12,000.00",
    stock: "10.00",
    allocated: "2.00",
    available: "8.00",
  },
  {
    id: 5,
    productCode: "1900004",
    makerCode: "メーカ084",
    no: "KP-20",
    name: "二連二重コンローバー",
    warehouse: "事務所0001-001",
    price: "12,000.00",
    stock: "10.00",
    allocated: "2.00",
    available: "8.00",
  },
  {
    id: 6,
    productCode: "1900004",
    makerCode: "メーカ084",
    no: "KP-20",
    name: "二連二重コンローバー",
    warehouse: "事務所0001-001",
    price: "12,000.00",
    stock: "10.00",
    allocated: "2.00",
    available: "8.00",
  },
  {
    id: 7,
    productCode: "1900004",
    makerCode: "メーカ084",
    no: "KP-20",
    name: "二連二重コンローバー",
    warehouse: "事務所0001-001",
    price: "12,000.00",
    stock: "10.00",
    allocated: "2.00",
    available: "8.00",
  },
  {
    id: 1,
    productCode: "1900004",
    makerCode: "メーカ084",
    no: "KP-20",
    name: "二連二重コンローバー",
    warehouse: "0001-001",
    price: "12,000.00",
    stock: "10.00",
    allocated: "2.00",
    available: "8.00",
  },
  {
    id: 2,
    productCode: "1900004",
    makerCode: "メーカ084",
    no: "KP-20",
    name: "二連二重コンローバー",
    warehouse: "事務所0001-001",
    price: "12,000.00",
    stock: "10.00",
    allocated: "2.00",
    available: "8.00",
  },
  {
    id: 3,
    productCode: "1900004",
    makerCode: "メーカ084",
    no: "KP-20",
    name: "二連二重コンローバー",
    warehouse: "0001-001",
    price: "12,000.00",
    stock: "10.00",
    allocated: "2.00",
    available: "8.00",
  },
  {
    id: 4,
    productCode: "1900004",
    makerCode: "メーカ084",
    no: "KP-20",
    name: "二連二重コンローバー",
    warehouse: "事務所0001-001",
    price: "12,000.00",
    stock: "10.00",
    allocated: "2.00",
    available: "8.00",
  },
  {
    id: 5,
    productCode: "1900004",
    makerCode: "メーカ084",
    no: "KP-20",
    name: "二連二重コンローバー",
    warehouse: "事務所0001-001",
    price: "12,000.00",
    stock: "10.00",
    allocated: "2.00",
    available: "8.00",
  },
  {
    id: 6,
    productCode: "1900004",
    makerCode: "メーカ084",
    no: "KP-20",
    name: "二連二重コンローバー",
    warehouse: "事務所0001-001",
    price: "12,000.00",
    stock: "10.00",
    allocated: "2.00",
    available: "8.00",
  },
  {
    id: 7,
    productCode: "1900004",
    makerCode: "メーカ084",
    no: "KP-20",
    name: "二連二重コンローバー",
    warehouse: "事務所0001-001",
    price: "12,000.00",
    stock: "10.00",
    allocated: "2.00",
    available: "8.00",
  },
];
export const fieldDefinitions = [
  {
    id: "0",
    selectLabel: "0中分類+小分類+メーカ",
    type: "multi-labeled",
    parts: [
      { label: "中分類", placeholder: "000", options: ["000", "001", "002"] },
      { label: "小分類", placeholder: "00", options: ["00", "01", "02"] },
      { label: "メーカ", placeholder: "000", options: ["000", "001", "002"] },
    ],
  },
  { id: "1", selectLabel: "1商品コード", label: "商品コード", type: "single" },
  { id: "2", selectLabel: "2商品名", label: "2商品名", type: "single" },
  { id: "3", selectLabel: "3型式", label: "型式", type: "single" },
  {
    id: "4",
    selectLabel: "4商品名+型式",
    label: "商品名+型式",
    type: "single",
  },
  {
    id: "5",
    selectLabel: "5商品名+メーカー名",
    label: "商品名+メーカー名",
    type: "single",
  },
] as const;

//SalesSlipEntryRegistration
export const fieldLabelMap: Record<string, string> = {
  productName: "商品名",
  supplierName: "仕入先",
  supplierCode: "仕入先コード",
  quantity: "数量",
  tax: "消費税",
  note: "備考",
  saleAmount: "売上金額",
  salesPrice: "売上単価",
  discountAmount: "値引金額",
  expenseNo: "経費分類No.",
  purchasePrice: "仕入単価",
  purchaseAmount: "仕入金額",
  supplier: "仕入先 ",
  expenseText: "経費分類No. ",
};

//LeftPanel
export const kanaButtons = [
  "ア",
  "カ",
  "サ",
  "タ",
  "ナ",
  "ハ",
  "マ",
  "ヤ",
  "ラ",
  "ワ",
  { label: "その他", wide: true },
  { label: "全て", wide: true },
];
export const tableHeaders = ["コード", "氏名", "カナ氏名", "所属事務所名"];
export const rowData = [
  "00000001",
  "担当者太郎",
  "タントウシャタロウ",
  "東京事務所03",
];
export const tableData = [
  {
    code: "00000001",
    name: "担当者 太郎",
    kana: "タントウシャ タロウ",
    office: "東京事務所03",
  },
  {
    code: "00000002",
    name: "顧客 次郎",
    kana: "コキャク ジロウ",
    office: "大阪事務所01",
  },
  {
    code: "00000003",
    name: "商品 三郎",
    kana: "ショウヒン サブロウ",
    office: "名古屋事務所02",
  },
  {
    code: "00000004",
    name: "山田 花子",
    kana: "ヤマダ ハナコ",
    office: "福岡事務所04",
  },
  {
    code: "00000005",
    name: "佐藤 一郎",
    kana: "サトウ イチロウ",
    office: "札幌事務所05",
  },
  {
    code: "00000006",
    name: "鈴木 健太",
    kana: "スズキ ケンタ",
    office: "東京事務所03",
  },
  {
    code: "00000007",
    name: "高橋 直子",
    kana: "タカハシ ナオコ",
    office: "広島事務所06",
  },
  {
    code: "00000008",
    name: "田中 雄大",
    kana: "タナカ ユウダイ",
    office: "仙台事務所07",
  },
];
export const colWidths = ["15%", "25%", "25%", "35%"];
export const fieldDefinitionsLeftPanel = [
  { id: "customerCode", label: "顧客コード", type: "double" },
  { id: "searchKey1", label: "検索キー１", type: "input" },
  { id: "searchKey2", label: "検索キー２", type: "input" },
  { id: "computerCode", label: "電算コード", type: "single" },
  { id: "eavesbarCode", label: "軒先バーコード", type: "input" },
  {
    id: "deleveryOrderCode",
    label: "配送順コード",
    type: "multi",
    partSizes: [50, 70, 50],
  },
  {
    id: "inspectionOderCode",
    label: "点検順コード",
    type: "multi",
    partSizes: [50, 70, 50],
  },
  {
    id: "saleOrderCode",
    label: "営業順コード",
    type: "multi",
    partSizes: [50, 70, 50],
  },
  {
    id: "meterReadingOrderCode",
    label: "検針順コード",
    type: "multi",
    partSizes: [50, 70, 50],
  },
  {
    id: "collectionOderCode",
    label: "集金順コード",
    type: "multi",
    partSizes: [50, 70, 50],
  },
  { id: "distributionCenterCD", label: "配送センターCD", type: "dropdown" },
  { id: "securityAgencyCD", label: "保安機関CD", type: "dropdown" },
  { id: "centralMonitoringCD", label: "集中監視CD", type: "dropdown" },
  { id: "oderManagementNo", label: "受注管理No.", type: "input" },
  { id: "deliverySlipNo", label: "出庫伝票No.", type: "input" },
] as const;
