//AdvanceSearchModal
export const fieldDefinitions = [
  { id: "allTel", label: "カナ氏名（あいまい）", type: "single" },
  {
    id: "customerCode",
    label: "顧客コード",
    type: "multi",
    partSizes: [45, 35, 65, 35],
  },
  { id: "searchCode1", label: "検索コード１", type: "single" },
  { id: "kanaName", label: "カナ氏名", type: "single" },
  { id: "securityCode", label: "保安機関コード", type: "dropdown" },
  { id: "searchCode2", label: "検索コード２", type: "single" },
  { id: "tel1", label: "電話番号１", type: "single" },
  {
    id: "meterRouteCode",
    label: "検針順コード",
    type: "multi",
    partSizes: [50, 40, 40],
  },
  {
    id: "keroseneCode",
    label: "灯油配達順コード",
    type: "multi",
    partSizes: [50, 40, 40],
  },
  { id: "tel2", label: "電話番号２", type: "single" },
  {
    id: "deliveryRouteCode",
    label: "配送順コード",
    type: "multi",
    partSizes: [50, 40, 40],
  },
  {
    id: "salesRepCode",
    label: "営業順コード",
    type: "multi",
    partSizes: [50, 40, 40],
  },
  { id: "tel3", label: "電話番号３", type: "single" },
  {
    id: "gMeterCode",
    label: "点検順コード",
    type: "multi",
    partSizes: [50, 40, 40],
  },
  {
    id: "chimneyCode",
    label: "集金順コード",
    type: "multi",
    partSizes: [50, 40, 40],
  },
  {
    id: "addressName",
    label: "住所＋カナ",
    type: "double",
    placeholders: ["住所", "カナ氏名"],
  },
  {
    id: "managementCenterCode",
    label: "集中管理センターコード",
    type: "dropdown",
  },
  { id: "deliveryCenterCode", label: "配送センターコード", type: "dropdown" },
  {
    id: "addressName",
    label: "住所名称＋カナ",
    type: "double",
    placeholders: ["住所名称", "カナ氏名"],
  },
  { id: "gasMeterSerial", label: "ガスメータ製造番号", type: "single" },
] as const;

// BalanceDetailScreen
export const detailsHeaders = [
  "日付",
  "伝票番号",
  "項目名",
  "売上金額（税込）",
  "入金金額",
  "残高",
  "自振対象",
];
export const categoryHeaders = [
  "項目名",
  "前月残高",
  "当月売上額",
  "当月入金額",
  "調整額・返品",
  "大分類別残高",
];
export const categoryItemNames = [
  "LPG",
  "ガス器具",
  "その他器具・工事",
  "リース",
  "大分類5",
  "大分類6",
  "大分類7",
  "大分類8",
  "大分類9",
  "電力",
  "その他",
  "",
  "",
  "",
  "",
  "",
  "割賦金",
];

//CheckSaleByCategoryScreen
export const labels = [
  "LPG",
  "ガス器具",
  "その他器具・工事",
  "リース",
  "大分類5",
  "大分類6",
  "大分類7",
  "大分類8",
  "大分類9",
  "電力",
  "割賦金",
  "その他",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "合計",
];
